name: 🌟 Refresh Content
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  refresh-cache:
    name: 🌟 Refresh Content
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '50'

      - name: 🛠 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 💿 Refresh Content
        run: node ./others/refresh-content.js
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
